FROM node:20-alpine

RUN apk add --no-cache postgresql16-client

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src ./src
COPY migrations ./migrations

EXPOSE 3000

CMD ["npx", "tsx", "watch", "src/index.ts"]
